{
 "title": "IoT Weather Monitoring influx",
 "description": "Iot lab",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "type": "grafana-clock-panel", "gridPos": { "h": 1, "w": 6, "x": 8, "y": 0 } },
  { "title": "Broker Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_user\" or r[\"_field\"] == \"usage_system\" or r[\"_field\"] == \"usage_nice\" or r[\"_field\"] == \"usage_softirq\" or r[\"_field\"] == \"usage_irq\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"available\" or r[\"_field\"] == \"used\" or r[\"_field\"] == \"total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "System",
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 10 },
   "options": {
    "content": "CPU: Intel i7-6700\r\nRAM: 8.00 GB"
   }
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_user\" or r[\"_field\"] == \"usage_system\" or r[\"_field\"] == \"usage_nice\" or r[\"_field\"] == \"usage_softirq\" or r[\"_field\"] == \"usage_irq\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"DESKTOP-V9OL7EV\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Connection Speed (Down/Up)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"internet_speed\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"download\" or r[\"_field\"] == \"upload\")\r\n  |> filter(fn: (r) => r[\"server_id\"] == \"10980\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Latency / Jitter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"internet_speed\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latency\" or r[\"_field\"] == \"jitter\")\r\n  |> filter(fn: (r) => r[\"server_id\"] == \"10980\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Average Last 24h",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: -24h) // Φιλτράρει τα δεδομένα από τις τελευταίες 24 ώρες\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Home/temperature\")\r\n  |> aggregateWindow(every: 1h, fn: mean) // Υπολογίζει το μέσο όρο ανά ώρα\r\n  |> yield(name: \"mean\")\r\n"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: -24h) // Φιλτράρει τα δεδομένα από τις τελευταίες 24 ώρες\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/temperatureIn\")\r\n  |> aggregateWindow(every: 1h, fn: mean) // Υπολογίζει το μέσο όρο ανά ώρα\r\n  |> yield(name: \"mean\")\r\n"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: -24h) // Φιλτράρει τα δεδομένα από τις τελευταίες 24 ώρες\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/temperatureOut\")\r\n  |> aggregateWindow(every: 1h, fn: mean) // Υπολογίζει το μέσο όρο ανά ώρα\r\n  |> yield(name: \"mean\")\r\n\r\n"
      }
     ]
    },
    {
     "title": "CO2",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: -24h) // Φιλτράρει τα δεδομένα από τις τελευταίες 24 ώρες\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Home/air\")\r\n  |> aggregateWindow(every: 1h, fn: mean) // Υπολογίζει το μέσο όρο ανά ώρα\r\n  |> yield(name: \"mean\")\r\n"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: -24h) // Φιλτράρει τα δεδομένα από τις τελευταίες 24 ώρες\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/airIn\")\r\n  |> aggregateWindow(every: 1h, fn: mean) // Υπολογίζει το μέσο όρο ανά ώρα\r\n  |> yield(name: \"mean\")\r\n"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: -24h) // Φιλτράρει τα δεδομένα από τις τελευταίες 24 ώρες\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/airOut\")\r\n  |> aggregateWindow(every: 1h, fn: mean) // Υπολογίζει το μέσο όρο ανά ώρα\r\n  |> yield(name: \"mean\")\r\n\r\n"
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: -24h) // Φιλτράρει τα δεδομένα από τις τελευταίες 24 ώρες\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Home/humidity\")\r\n  |> aggregateWindow(every: 1h, fn: mean) // Υπολογίζει το μέσο όρο ανά ώρα\r\n  |> yield(name: \"mean\")\r\n"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: -24h) // Φιλτράρει τα δεδομένα από τις τελευταίες 24 ώρες\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/humidityIn\")\r\n  |> aggregateWindow(every: 1h, fn: mean) // Υπολογίζει το μέσο όρο ανά ώρα\r\n  |> yield(name: \"mean\")\r\n"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: -24h) // Φιλτράρει τα δεδομένα από τις τελευταίες 24 ώρες\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/humidityOut\")\r\n  |> aggregateWindow(every: 1h, fn: mean) // Υπολογίζει το μέσο όρο ανά ώρα\r\n  |> yield(name: \"mean\")\r\n\r\n"
      }
     ]
    },
    {
     "title": "Toluene",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: -24h) // Φιλτράρει τα δεδομένα από τις τελευταίες 24 ώρες\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Home/airToluene\")\r\n  |> aggregateWindow(every: 1h, fn: mean) // Υπολογίζει το μέσο όρο ανά ώρα\r\n  |> yield(name: \"mean\")\r\n"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: -24h) // Φιλτράρει τα δεδομένα από τις τελευταίες 24 ώρες\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/airTolueneIn\")\r\n  |> aggregateWindow(every: 1h, fn: mean) // Υπολογίζει το μέσο όρο ανά ώρα\r\n  |> yield(name: \"mean\")\r\n"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: -24h) // Φιλτράρει τα δεδομένα από τις τελευταίες 24 ώρες\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/airTolueneOut\")\r\n  |> aggregateWindow(every: 1h, fn: mean) // Υπολογίζει το μέσο όρο ανά ώρα\r\n  |> yield(name: \"mean\")\r\n\r\n"
      }
     ]
    },
    {
     "title": "Luminosity",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: -24h) // Φιλτράρει τα δεδομένα από τις τελευταίες 24 ώρες\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Home/light\")\r\n  |> aggregateWindow(every: 1h, fn: mean) // Υπολογίζει το μέσο όρο ανά ώρα\r\n  |> yield(name: \"mean\")\r\n"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: -24h) // Φιλτράρει τα δεδομένα από τις τελευταίες 24 ώρες\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/lightIn\")\r\n  |> aggregateWindow(every: 1h, fn: mean) // Υπολογίζει το μέσο όρο ανά ώρα\r\n  |> yield(name: \"mean\")\r\n"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: -24h) // Φιλτράρει τα δεδομένα από τις τελευταίες 24 ώρες\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/lightOut\")\r\n  |> aggregateWindow(every: 1h, fn: mean) // Υπολογίζει το μέσο όρο ανά ώρα\r\n  |> yield(name: \"mean\")\r\n\r\n"
      }
     ]
    },
    {
     "title": "NH4",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: -24h) // Φιλτράρει τα δεδομένα από τις τελευταίες 24 ώρες\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Home/NH4\")\r\n  |> aggregateWindow(every: 1h, fn: mean) // Υπολογίζει το μέσο όρο ανά ώρα\r\n  |> yield(name: \"mean\")\r\n"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: -24h) // Φιλτράρει τα δεδομένα από τις τελευταίες 24 ώρες\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/NH4In\")\r\n  |> aggregateWindow(every: 1h, fn: mean) // Υπολογίζει το μέσο όρο ανά ώρα\r\n  |> yield(name: \"mean\")\r\n"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: -24h) // Φιλτράρει τα δεδομένα από τις τελευταίες 24 ώρες\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/NH4Out\")\r\n  |> aggregateWindow(every: 1h, fn: mean) // Υπολογίζει το μέσο όρο ανά ώρα\r\n  |> yield(name: \"mean\")\r\n\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Compare",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Home/temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/temperatureIn\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/temperatureOut\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Home/humidity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/humidityIn\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/humidityOut\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Luminosity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Home/light\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/lightIn\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/lightOut\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "CO2",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Home/air\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/airIn\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/airOut\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Toluene",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 7, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Home/airToluene\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/airTolueneIn\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/airTolueneOut\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "NH4",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 14, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Home/NH4\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/NH4In\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/NH4Out\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Home",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature Home",
     "type": "timeseries",
     "description": "Home Temperature C",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Home/temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Humidity Home",
     "type": "timeseries",
     "description": "Home Humidity %",
     "gridPos": { "h": 7, "w": 7, "x": 7, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Home/humidity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Air Quality Home",
     "type": "timeseries",
     "description": "Home Air Quality (CO2)  & Toluene ",
     "gridPos": { "h": 7, "w": 7, "x": 14, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Home/air\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Home/airToluene\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Home/NH4\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Luminosity Home",
     "type": "timeseries",
     "description": "Home Luminosity %",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "  from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Home/light\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "gauge",
     "description": "Gauge for Temperature home",
     "gridPos": { "h": 6, "w": 3, "x": 7, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"DESKTOP-V9OL7EV\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Home/temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "gauge",
     "description": "Gauge for Humidity home",
     "gridPos": { "h": 6, "w": 3, "x": 10, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"DESKTOP-V9OL7EV\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Home/humidity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "CO2",
     "type": "gauge",
     "description": "Gauge for Air Quality home",
     "gridPos": { "h": 4, "w": 3, "x": 13, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"DESKTOP-V9OL7EV\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Home/air\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Toluene",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 2, "x": 16, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"DESKTOP-V9OL7EV\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Home/airToluene\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "NH4",
     "type": "gauge",
     "description": "Gauge for Air Quality NH4 home",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"DESKTOP-V9OL7EV\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Home/NH4\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Work Inside",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature Work inside",
     "type": "timeseries",
     "description": "Work Temperature C inside",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/temperatureIn\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Humidity Work inside",
     "type": "timeseries",
     "description": "Work Humidity % inside",
     "gridPos": { "h": 7, "w": 7, "x": 7, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/humidityIn\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Air Quality Work inside",
     "type": "timeseries",
     "description": "Work Air Quality (CO2), Toluene % NH4 inside",
     "gridPos": { "h": 7, "w": 7, "x": 14, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/airIn\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/airTolueneIn\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/NH4In\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Luminosity Work inside",
     "type": "timeseries",
     "description": "Work Luminosity % inside",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/lightIn\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "gauge",
     "description": "Gauge for Temperature inside",
     "gridPos": { "h": 6, "w": 3, "x": 7, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/temperatureIn\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "gauge",
     "description": "Gauge for Humidity work in",
     "gridPos": { "h": 6, "w": 3, "x": 10, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/humidityIn\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "CO2",
     "type": "gauge",
     "description": "Gauge for Air Quality Work in",
     "gridPos": { "h": 4, "w": 3, "x": 13, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"DESKTOP-V9OL7EV\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/airIn\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Toluene",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 2, "x": 16, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/airTolueneIn\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "NH4",
     "type": "gauge",
     "description": "Gauge for Air Quality NH4 work in",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/NH4In\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Work Outside",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature Work outside",
     "type": "timeseries",
     "description": "Work Temperature C outside",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/temperatureOut\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Humidity Work outside",
     "type": "timeseries",
     "description": "Work Humidity % outside",
     "gridPos": { "h": 7, "w": 7, "x": 7, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/humidityOut\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Air Quality Work outside",
     "type": "timeseries",
     "description": "Work Air Quality (CO2), Toluene & NH4 outside",
     "gridPos": { "h": 7, "w": 7, "x": 14, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/airOut\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/airTolueneOut\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/NH4Out\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Luminosity Work outside",
     "type": "timeseries",
     "description": "Work Luminosity % outside",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/lightOut\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "gauge",
     "description": "Gauge for Temperature outside",
     "gridPos": { "h": 6, "w": 3, "x": 7, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/temperatureOut\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "gauge",
     "description": "Gauge for Humidity work out",
     "gridPos": { "h": 6, "w": 3, "x": 10, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/humidityOut\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "CO2",
     "type": "gauge",
     "description": "Gauge for Air Quality outside",
     "gridPos": { "h": 4, "w": 3, "x": 13, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/airOut\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Toluene",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 2, "x": 16, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/airTolueneOut\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "NH4",
     "type": "gauge",
     "description": "Gauge for Air Quality NH4 work out",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Omiros/Work/NH4Out\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  }
 ]
}